### ISSUE TITLE
Correzioni DLC

### ISSUE THREAD

**Issue by Neurone** [Neurone/dd-italian-for-italians#17]
Da @vampucio: _Vorrei caricare anche i file dei dlc (sia free che a pagamento) però non so come fare e non so se creano problemi a chi non ha il dlc. Nel dlc gli errori sono pochissimi ma ci sono_

**Comment by Neurone** [comment]
Puoi fare sempre tutto online, se i file non sono molti. E non dovrebbero visto che mi dici che sono poche le correzioni e per un mod è sufficiente caricare solamente i file modificati, non tutti. Quanti e quali file vorresti creare? I file aggiuntivi comunque non daranno problemi a chi non ha il DLC specifico.

**Comment by vampucio** [comment]
DarkestDungeon\dlc\580100_crimson_court\localization\CC.string_table.xml
DarkestDungeon\dlc\702540_shieldbreaker\localization\shieldbreaker.string_table.xml

sono rispettivamente dell'espansione della corte e della frangi scudi. entrambi hanno errori da correggere

**Comment by Neurone** [comment]
Creati i file, puoi modificarli.

**Comment by vampucio** [comment]
come devo comportarmi? devo inserire tutto il file dentro? solo la lingua italiana? come si fa poi a dire al gioco che il file è in una cartella diversa da quella degli altri file di localizzazione?

**Comment by Neurone** [comment]
Mmm... in che senso in una cartella diversa? quella cartella DLC sta dentro la cartella DD ufficiale o una cartella a parte di steam?

Per il contenuto, fai come per il resto dei file: togli tutto tranne l'intestazione inglese e la lingua italiana, che devi comunque mettere per intero. Deve venire quindi così:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <language id="english"/>
  <language id="italian">
```
...
```xml
  </language>
</root>
```

**Comment by vampucio** [comment]
sono della root ufficiale del gioco come ti ho scritto sopra, ma gli altri file che stavamo modificando sono in

DarkestDungeon\localization\

per questo ho chiesto, cmq comincio a popolare i file con tutto il testo italiano

EDIT: mi spiego meglio. le normali traduzioni sono in

DarkestDungeon\localization\

le altre 2 dei dlc

DarkestDungeon\dlc\580100_crimson_court\localization\
DarkestDungeon\dlc\702540_shieldbreaker\localization\

ho chiesto perchè non so come steam pesca le mod e non so se va fatto il tree anche qui o non c'è bisogno

**Comment by Neurone** [comment]
Capito. Allora no, serve rispettare la struttura delle cartelle, e inoltre vanno compilati correttamente i file `.loc2` per quelle traduzioni. Dovrebbe fare tutto l'uploader di steam, altrimenti serve che lo faccio a mano. Puoi verificare se dentro quelle due cartelle c'è un file che si chiama `localization.bat` e se sì, puoi dirmi cosa c'è scritto dentro?

**Comment by vampucio** [comment]
frangiscudi

START ../../../_windows/localization.exe -prefix shieldbreaker

corte

START ../../../_windows/localization.exe -prefix CC

**Comment by Neurone** [comment]
Thanks. Si complica un po' lo script per l'aggiornamento del mod su Steam, ma ho già fatto delle prove e riesco a modifare la traduzione di un mod, quindi dovrebbe funzionare. Appena aggiorno il mod ti avverto e mi fai sapere se funziona.

**Comment by Neurone** [comment]
Come non detto. Era Steam che non aveva aggiornato correttamente il mod, il tutto funziona semplicemente avendo i file nella cartella localization insieme agli altri. Più semplice. A breve creo una release così poi mi dici se funziona tutto :)

**Comment by vampucio** [comment]
ok grazie mille, poi appena ho un attimo inizio a mettere anche alcuni fix dei dlc. Purtroppo credo che prima di lunedì non riesco. cmq grazie ancora ^_^

**Comment by Neurone** [comment]
Rilasciata release v1.6.0 :) E' venuto fuori però un bug #23 che per ora non penso riusciremo a risolvere, quindi dagli un'occhiata prima di aggiungere altre traduzioni perché potrebbero ricadere in quella casistica.
