### ISSUE TITLE
Abilità frangiscudi

### ISSUE THREAD

**Issue by vampucio** [Neurone/dd-italian-for-italians#27]
L'abilità in inglese "puntura" è stata tradotta come "intontimento" capisco che puntura faccia cagare (l'animazione è lei che attacca il nemico con la lancia e in trasparenza c'è il cobra che esce dalla lancia) ma morso è già un'abilità. Come credi si possa adattare bene? non mi viene un'idea

**Comment by Neurone** [comment]
A parte che appunto _intontimento_ è proprio sbagliato, per me _Puntura_ come traduzione di _Puncture_ è corretto. Considera che anche per un inglese la parola _puncture_ significa semplicemente _puntura_, e il fatto che il nome dell'abilità non sia _altisonante_ è sicuramente voluto.

**Comment by vampucio** [comment]
procedo con puntura allora
